site_name: 文 档
site_url: https://bibaijin.github.io/tutorial
site_description: 一些技术的使用技巧及心得
site_author: bibaijin

repo_url: https://github.com/bibaijin/tutorial

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 主页: index.md
- Haskell: haskell.md
- LaTeX: LaTeX.md
- Python:
    - Built-in: python/built-in.md
    - Django: python/django.md
    - Matplotlib: python/matplotlib.md
    - MkDocs: python/mkdocs.md
- Linux:
    - OS: linux/os.md
    - Shell: linux/shell.md
- PostgreSQL: postgresql.md
- Git: git.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">金比白</a>.
